#!/usr/bin/perl

print STDERR "@ARGV\n";

$fname = $ARGV[0];

while (<>) {
	last if /<table cellspacing=0 cellpadding=0 border=0>/;
}

for ($i = 0; $i < 14; $i++) {
	$line[$i] = <>;

	chomp $line[$i];
	$line[$i] =~ s/\015//g;
	$line[$i] =~ s/<\/p><\/th>//;
	$line[$i] =~ s/  <th valign=TOP nowrap><p>//;
	$line[$i] =~ s/  <th valign=TOP align=LEFT nowrap><p>//;
}

$line[13] =~ s/Weather: //;
$line[11] =~ s/Coordinate: //;
$line[3] =~ s/,//g;

$weather = $line[13];
$coord = $line[11];
$name = $line[5];
$date = $line[3];

# print "$weather\n$coord\n$name\n$date\n";

open(IN, "intersection_movements_traffic_counts.kml");
while (<IN>) {
	if (/coordinate=$coord/) {
		$found = 1;
	}

	if (/<coordinates>([0-9.-]*),([0-9.-]*)/) {
		if ($found) {
			$lon = $1;
			$lat = $2;
			last;
		}
	}
}

while (<>) {
	chomp;
	s/\015//;

	if (/^<tr><th>(North|South|East|West)/) {
		s/ class='[bg]'//g;
		s/<\/th>//g;
		s/<\/TH>//g;
		s/<BR>/ /g;
		s/<tr>//g;
		s/ +/ /g;
		s/^<th>//;
		s/<th>/,/g;
		s/ *,/,/g;

		@headers = split(/, */);
		$direction = $headers[0];

		# print;
	}

	if (/<tr><th class='[bg]' nowrap>(AM|PM) Max Hour/) {
		s/ class='[bg]'//g;
		s/ nowrap//g;
		s/<\/th>//g;
		s/<\/TH>//g;
		s/<\/td>//g;
		s/<\/TD>//g;
		s/<BR>/ /g;
		s/<tr>//g;
		s/ +/ /g;
		s/^<th>//;
		s/<TD>/,/g;
		s/<th>/,/g;
		s/ *,/,/g;

		@cols = split(/, */);
		$peak_time = $cols[0];
		$times{$peak_time} = 1;

		for ($i = 1; $i <= $#cols; $i++) {
			if ($headers[$i] =~ /Left/) {
				$peak{$peak_time}{'left'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Right/) {
				$peak{$peak_time}{'right'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Thru/) {
				$peak{$peak_time}{'thru'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Bikes/) {
				$peak{$peak_time}{'bikes'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Peds/) {
				$peak{$peak_time}{'peds'}{$direction} += $cols[$i];
			}
		}
	}

	if (/<tr><th class='[bg]' nowrap>2 Hour Totals/) {
		s/ class='[bg]'//g;
		s/ nowrap//g;
		s/<\/th>//g;
		s/<\/TH>//g;
		s/<\/td>//g;
		s/<\/TD>//g;
		s/<BR>/ /g;
		s/<br>/ /g;
		s/<tr>//g;
		s/ +/ /g;
		s/^<th>//;
		s/<TD>/,/g;
		s/<th>/,/g;
		s/ *,/,/g;

		@cols = split(/, */);
		$peak_time = $cols[0];
		$times{$peak_time} = 1;

		for ($i = 1; $i <= $#cols; $i++) {
			if ($headers[$i] =~ /Left/) {
				$peak{$peak_time}{'left'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Right/) {
				$peak{$peak_time}{'right'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Thru/) {
				$peak{$peak_time}{'thru'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Bikes/) {
				$peak{$peak_time}{'bikes'}{$direction} += $cols[$i];
			}
			if ($headers[$i] =~ /Peds/) {
				$peak{$peak_time}{'peds'}{$direction} += $cols[$i];
			}
		}
	}

	if (/<table border=1 cellspacing=0 cellpadding=0 width=350>/) {
	}
}

for $time (sort(keys(%times))) {
	$t2 = $time;
	$t2 =~ s/2 Hour Totals //;
	$t2 =~ s/.M Max Hour //;
	$t2 =~ s/ //g;

	print "vancouver/cfapp.vancouver.ca/vanmapmtc_wa/$fname,$name,$coord,$date,$t2,";

	for $direction ("North", "East", "South", "West") {
		print "$peak{$time}{'right'}{$direction},$peak{$time}{'thru'}{$direction},$peak{$time}{'left'}{$direction},";
	}
	for $direction ("North", "East", "South", "West") {
		print "$peak{$time}{'peds'}{$direction},";
	}
	for $direction ("North", "East", "South", "West") {
		print "$peak{$time}{'bikes'}{$direction},";
	}

	print "$lat,$lon,$weather";
	print "\n";
}

