#!/usr/bin/perl

for ($i = 0; $i < 71; $i++) {
	$line[$i] = <>;

	chomp $line[$i];
	$line[$i] =~ s/\015//g;
	$line[$i] =~ s/<\/p><\/th>//;
	$line[$i] =~ s/  <th valign=TOP nowrap><p>//;
	$line[$i] =~ s/  <th valign=TOP align=LEFT nowrap><p>//;
}

$line[68] =~ s/Weather: //;
$line[66] =~ s/Coordinate: //;
$line[58] =~ s/,//g;

print "$line[68]\n";
print "$line[66]\n";
print "$line[60]\n";
print "$line[58]\n";

$coord = $line[66];

open(IN, "intersection_movements_traffic_counts.kml");
while (<IN>) {
	if (/coordinate=$coord/) {
		$found = 1;
	}

	if (/<coordinates>([0-9.-]*),([0-9.-]*)/) {
		if ($found) {
			$lon = $1;
			$lat = $2;
			last;
		}
	}
}

print "$lat,$lon\n";

while (<>) {
	if (/^<tr><th>(North|South|East|West)/) {
		s/ class='g'//g;
		s/<\/th>//g;
		s/<\/TH>//g;
		s/<BR>/ /g;
		s/<tr>//g;
		s/ +/ /g;
		s/^<th>//;
		s/<th>/,/g;
		s/ *,/,/g;

		print;
	}

	if (/<tr><th class='g' nowrap>(AM|PM) Max Hour/) {
		s/ class='g'//g;
		s/ nowrap//g;
		s/<\/th>//g;
		s/<\/TH>//g;
		s/<\/td>//g;
		s/<\/TD>//g;
		s/<BR>/ /g;
		s/<tr>//g;
		s/ +/ /g;
		s/^<th>//;
		s/<TD>/,/g;
		s/<th>/,/g;
		s/ *,/,/g;

		print;
	}

	if (/<tr><th class='g' nowrap>2 Hour Totals/) {
		s/ class='g'//g;
		s/ nowrap//g;
		s/<\/th>//g;
		s/<\/TH>//g;
		s/<\/td>//g;
		s/<\/TD>//g;
		s/<BR>/ /g;
		s/<br>/ /g;
		s/<tr>//g;
		s/ +/ /g;
		s/^<th>//;
		s/<TD>/,/g;
		s/<th>/,/g;
		s/ *,/,/g;

		print;
	}

	if (/<table border=1 cellspacing=0 cellpadding=0 width=350>/) {
		print "\n";
	}
}

print "\n\n";
